# Generated by Django 3.1.5 on 2021-07-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DCS1', '0002_auto_20210729_1539'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DairyProducts',
            new_name='Products',
        ),
    ]
