# Generated by Django 3.2.5 on 2021-07-31 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DCS1', '0003_auto_20210730_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='bar_img',
        ),
    ]
